import {
    ExclamationCircleFilled,
    EditOutlined,
    FileDoneOutlined,
    FileOutlined,
    FilePdfOutlined,
    FileWordOutlined,
    LockOutlined,
    UserOutlined,
    LoadingOutlined,
} from "@ant-design/icons";

import {
    MdOutlineDarkMode,
    MdOutlineWbSunny,
    MdNewReleases,
    MdPublishedWithChanges,
    MdSettings,
    MdPassword,
    MdZoomIn,
    MdZoomOut,
    MdContentCopy,
    MdImage,
    MdHideImage,
    MdFullscreen,
    MdFullscreenExit,
    MdOutlineZoomOut,
    MdOutlineZoomIn,
    MdImageSearch,
} from "react-icons/md";

import {
    FaUser,
    FaBars,
    FaGlasses,
    FaRegFile,
    FaGlobe,
    FaTrash,
    FaAlignJustify,
    FaEdit,
    FaPlusCircle,
    FaPlus,
    FaRegCalendarPlus,
    FaSort,
    FaSortAlphaUp,
    FaSortAmountDown,
    FaSortAmountUp,
    FaTags,
    FaHome,
    FaTag,
    FaRegHeart,
    FaEye,
    FaPen,
    FaPenAlt,
    FaCheck,
    FaChevronDown,
    FaFile,
    FaFileAlt,
    FaFileSignature,
    FaFilter,
    FaStarOfLife,
    FaFeatherAlt,
    FaPenFancy,
    FaRegSave,
    FaBook,
    FaCloudUploadAlt,
    FaBookOpen,
    FaUserCircle,
    FaSignOutAlt,
    FaRegFileAlt,
    FaRegFilePdf,
    FaRegClone,
    FaNewspaper,
    FaTimesCircle,
    FaAngleRight,
    FaAngleLeft,
    FaCheckCircle,
    FaFilePdf,
    FaArrowRight,
    FaArrowLeft,
    FaFileImage,
    FaFileUpload,
    FaFileDownload,
    FaCogs,
    FaRegListAlt,
    FaRegImage,
    FaTrashAlt,
    FaRegTimesCircle,
    FaRegCheckCircle,
    FaCircleNotch,
    FaGripLines,
    FaRegKeyboard,
    FaLayerGroup,
    FaPencilAlt,
    FaHourglass,
    FaRedo,
    FaUpload,
    FaUserAlt,
    FaTasks,
    FaUserFriends,
    FaUserSlash,
    FaSave,
    FaRegFileWord,
    FaRegHourglass,
    FaUsers,
} from "react-icons/fa";

import { FaFileArrowUp, FaFileCirclePlus, FaFileZipper } from "react-icons/fa6";

import { AiOutlineCopy } from "react-icons/ai";

import {
    FiEdit,
    FiLayers,
    FiLogIn,
    FiLogOut,
    FiTrash,
    FiEdit2,
} from "react-icons/fi";
import {
    ImMenu4,
    ImFileText2,
    ImBooks,
    ImNewspaper,
    ImProfile,
    ImLibrary,
} from "react-icons/im";

import { PiTextColumnsBold, PiFileTextLight } from "react-icons/pi";
import { VscLayersActive, VscBook } from "react-icons/vsc";
import { SlCalender } from "react-icons/sl";
import { GiStack, GiNewspaper } from "react-icons/gi";
import { TiDocumentText } from "react-icons/ti";

import { TbSettingsCode, TbSettingsDown } from "react-icons/tb";
import { IoIosCloseCircle } from "react-icons/io";
import { BsFileEarmarkFont } from "react-icons/bs";

export {
    AiOutlineCopy,
    BsFileEarmarkFont,
    EditOutlined,
    LoadingOutlined,
    ExclamationCircleFilled,
    FaAlignJustify,
    FaAngleLeft,
    FaAngleRight,
    FaArrowLeft,
    FaArrowRight,
    FaBars,
    FaBook,
    FaBookOpen,
    FaCogs,
    FaCheck,
    FaCheckCircle,
    FaChevronDown,
    FaCircleNotch,
    FaCloudUploadAlt,
    FaEdit,
    FaEye,
    FaFeatherAlt,
    FaFile,
    FaFileAlt,
    FaFileArrowUp,
    FaFileCirclePlus,
    FaFileDownload,
    FaFileImage,
    FaFilePdf,
    FaFileSignature,
    FaFileUpload,
    FaFilter,
    FaGlasses,
    FaGlobe,
    FaGripLines,
    FaHome,
    FaHourglass,
    FaLayerGroup,
    FaNewspaper,
    FaPencilAlt,
    FaPen,
    FaPenAlt,
    FaPenFancy,
    FaPlus,
    FaPlusCircle,
    FaRedo,
    FaRegCalendarPlus,
    FaRegCheckCircle,
    FaRegClone,
    FaRegFile,
    FaRegFileAlt,
    FaRegFilePdf,
    FaRegFileWord,
    FaRegHeart,
    FaRegImage,
    FaRegKeyboard,
    FaRegListAlt,
    FaRegSave,
    FaRegTimesCircle,
    FaRegHourglass,
    FaUsers,
    FaFileZipper,
    FaSave,
    FaSignOutAlt,
    FaSort,
    FaSortAlphaUp,
    FaSortAmountDown,
    FaSortAmountUp,
    FaStarOfLife,
    FaTag,
    FaTags,
    FaTasks,
    FaTimesCircle,
    FaTrash,
    FaTrashAlt,
    FaUpload,
    FaUser,
    FaUserAlt,
    FaUserCircle,
    FaUserFriends,
    FaUserSlash,
    FiEdit,
    FiEdit2,
    FiLayers,
    FiLogIn,
    FiLogOut,
    FiTrash,
    FileDoneOutlined,
    FileOutlined,
    FilePdfOutlined,
    FileWordOutlined,
    GiNewspaper,
    GiStack,
    ImBooks,
    ImFileText2,
    ImLibrary,
    ImMenu4,
    ImNewspaper,
    ImProfile,
    IoIosCloseCircle,
    LockOutlined,
    MdContentCopy,
    MdFullscreen,
    MdFullscreenExit,
    MdHideImage,
    MdImage,
    MdImageSearch,
    MdNewReleases,
    MdOutlineDarkMode,
    MdOutlineWbSunny,
    MdOutlineZoomIn,
    MdOutlineZoomOut,
    MdPassword,
    MdPublishedWithChanges,
    MdSettings,
    MdZoomIn,
    MdZoomOut,
    PiFileTextLight,
    PiTextColumnsBold,
    SlCalender,
    TbSettingsCode,
    TbSettingsDown,
    TiDocumentText,
    UserOutlined,
    VscBook,
    VscLayersActive,
};
